models:
  - generation_engine: gemini
    model: gemini-2.0-flash-001
model_selection: random
prompt_templates:
  - prompt_template: api-prompts/basic_answer_refined
template_selection: all
retrieval:
  - retrieval_window: 0
    top_k: 20
retrieval_selection: random
documents_per_query: 1 # set this to 1 if the query file contains document ids
