users:
  - tamara_bajkusa_spahic
  - kakhaberi_mdivani
  - didar_batryshev
  - matt_pagett
  - raymond_pilcher
  - c_ozgen_karacan
  - justyna_swolkien
  - francesco_pizzocolo
  - carolina_coll
  - ilaria_conti
  - toyo_kawabata
  - romanas_savickas
  - henri_paillere
  - roberta_boscolo
  - jinsun_lim
  - giulia_manconi
  - silvia_martinez_romero
  - bertrand_magne
  - piyush_verma
  - marina_gil_sevilla
  - sean_ratka
  - anna_piwowarska
  - andrei_covatariu
  - hamid_bastani
  - iva_brkic
  - dario_liguti
annotations_per_record: 3