models:
  - generation_engine: openai
    model: gpt-3.5-turbo
  - generation_engine: openai
    model: gpt-4-turbo
  - generation_engine: huggingface
    model: mistralai/Mistral-7B-Instruct-v0.2
  - generation_engine: gemini
    model: gemini-2.0-flash-001
model_selection: random
prompt_templates:
  - prompt_template: response/FAITHFULQA_SCHIMANSKI_CITATION_QA_TEMPLATE_MODIFIED
  - prompt_template: response/adversarial
template_selection: all
retrieval:
  - retrieval_window: 1
    top_k: 3
  - retrieval_window: 0
    top_k: 6
retrieval_selection: random
documents_per_query: 1 # set this to 1 if the query file contains document ids