models:
  - generation_engine: gemini
    model: gemini-1.5-flash
model_selection: all
prompt_templates:
  - prompt_template: evals-0.0.1/queries-ambiguous
  - prompt_template: evals-0.0.1/queries-bias-equity-risk
  - prompt_template: evals-0.0.1/queries-climate-controversy
  - prompt_template: evals-0.0.1/queries-controversial
  - prompt_template: evals-0.0.1/queries-factual-errors
  - prompt_template: evals-0.0.1/queries-harmful
  - prompt_template: evals-0.0.1/queries-indigenous
  - prompt_template: evals-0.0.1/queries-long
  - prompt_template: evals-0.0.1/queries-normal
  - prompt_template: evals-0.0.1/queries-search-terms
  - prompt_template: evals-0.0.1/queries-sections
  - prompt_template: evals-0.0.1/queries-speculative
  - prompt_template: evals-0.0.1/queries-typo
template_selection: all
seed_queries_path: data/seed_samples.jsonl
retrieval:
  - retrieval_window: 1
    top_k: 6
retrieval_selection: random
documents_per_query: 1 # set this to 1 if the query file contains document ids