models:
  - generation_engine: vertexai
    model: mistral-large
  - generation_engine: vertexai
    model: llama3-70b
  - generation_engine: gemini
    model: gemini-1.5-pro
  - generation_engine: vertexai
    model: climate-gpt-7b
  - generation_engine: vertexai
    model: llama3-1-8b-instruct
model_selection: all
prompt_templates:
  - prompt_template: no-answers-test/response_qa_relax_henry_1
  - prompt_template: no-answers-test/response_qa_relax_henry_2
  - prompt_template: no-answers-test/basic_answer_response_educational
  - prompt_template: no-answers-test/basic_answer_response_query_analysis
template_selection: all
retrieval:
  - retrieval_window: 1
    top_k: 6
retrieval_selection: random
documents_per_query: 1 # set this to 1 if the query file contains document ids