models:
  - generation_engine: gemini
    model: gemini-1.5-flash
model_selection: all
prompt_templates:
  - prompt_template: main-experiment/queries-normal
  - prompt_template: main-experiment/queries-typo
  - prompt_template: main-experiment/queries-speculative
  - prompt_template: main-experiment/queries-sections
  - prompt_template: main-experiment/queries-policy-violation
  - prompt_template: main-experiment/queries-numerical
  - prompt_template: main-experiment/queries-long
  - prompt_template: main-experiment/queries-indigenous
  - prompt_template: main-experiment/queries-harmful
  - prompt_template: main-experiment/queries-controversial
  - prompt_template: main-experiment/queries-search-terms
  - prompt_template: main-experiment/queries-no-answer
  - prompt_template: main-experiment/queries-bias-equity-risk
  - prompt_template: main-experiment/queries-ambiguous
template_selection: all
seed_queries_path: data/seed_samples.jsonl
retrieval:
  - retrieval_window: 1
    top_k: 6
retrieval_selection: random
documents_per_query: 1 # set this to 1 if the query file contains document ids