models:
  - generation_engine: vertexai
    model: llama3-1-70b-instruct
model_selection: all
prompt_templates:
  - prompt_template: no-answers-test/response_qa_relax_henry_1
  - prompt_template: no-answers-test/response_qa_relax_henry_2
  - prompt_template: no-answers-test/basic_answer_response_educational
  - prompt_template: no-answers-test/basic_answer_response_query_analysis
template_selection: all
retrieval:
  - retrieval_window: 1
    top_k: 6
retrieval_selection: random
documents_per_query: 1 # set this to 1 if the query file contains document ids