models:
  - generation_engine: vertexai
    model: llama3-1-70b-instruct
  - generation_engine: vertexai
    model: climate-gpt-7b
  - generation_engine: gemini
    model: gemini-1.5-flash
  - generation_engine: gemini
    model: gemini-1.5-pro
  - generation_engine: vertexai
    model: llama3-1-8b-instruct
  - generation_engine: vertexai
    model: llama3-70b
model_selection: all
prompt_templates:
  - prompt_template: evals-answers-0.0.1/basic_answer
template_selection: all
retrieval:
  - retrieval_window: 1
    top_k: 6
retrieval_selection: random
documents_per_query: 1 # set this to 1 if the query file contains document ids