models:
  - generation_engine: vertexai
    model: mistral-nemo
model_selection: all
prompt_templates:
  - prompt_template: evals-answers-0.0.1/kg_intermediate
template_selection: all
retrieval:
  - retrieval_window: 1
    top_k: 3
retrieval_selection: random
documents_per_query: 1 # set this to 1 if the query file contains document ids