name: test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry==1.3.2

      - name: Install python or load from cache with dependencies
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"
          
      - name: Install dependencies
        run: |
          poetry install && poetry run pre-commit install
  
      - name: Install NLTK dependencies
        run: |
          poetry run python -m nltk.downloader stopwords
          poetry run python -m nltk.downloader punkt

      - name: Run test suite
        env:
          GOOGLE_APPLICATION_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          poetry run python -m pytest \
          --ignore=tests/online/test_online_helpers.py \
          --ignore=tests/test_db.py \
          --ignore=tests/dataset_creation/test_iaa.py \
          --ignore=tests/controllers/test_document_controller.py \
          --ignore=notebooks/first_round_eval_analysis.ipynb \
          --ignore=notebooks/system_prompts.ipynb \
          --ignore=tests/controllers/test_rag_controller.py \
          --ignore=tests/ingestion/test_ingestion_helpers.py \
          --ignore=tests/controllers/test_vespa_controller.py \
          --nbmake \
          --nbmake-find-import-errors \
          --nbmake-timeout=20 -vvv